import numpy as np

# Image reading (READ)
READ_COLOR = 0
READ_GRAY = 1

# Color conversion (COLOR)
COLOR_RGB2BGR = 0
COLOR_BGR2RGB = 1
COLOR_RGB2GRAY = 2
COLOR_GRAY2RGB = 3
COLOR_RGB2RGBA = 4
COLOR_RGBA2RGB = 5
COLOR_RGB2HSV = 6
COLOR_HSV2RGB = 7
COLOR_RGB2HSL = 8
COLOR_HSL2RGB = 9
COLOR_RGB2LAB = 10
COLOR_LAB2RGB = 11

# Thresholding (THRESH)
THRESH_BINARY = 0
THRESH_INVERSE = 1
THRESH_TOZERO = 2
THRESH_TOMAX = 3
THRESH_OTSU = 4

# Image morphology (MORPH)
MORPH_SQUARE = 0
MORPH_CIRCLE = 1
MORPH_CROSS = 2